top-level = [ figure, [{ figure-delimiter, [figure] }] ];
figure = [ statement, [{ statement-delimiter, [ statement ] }] ];
statement = keyword, [ arguments ], [{ property-delimiter, property }];

arguments = tuple;
property = ? identifier ?, [ arguments ];
comment = "#", [ atom ]

atom = literal | tuple | list
keyword = "plot"
	| "default"
	| "overwrite" | "ow"
	| "axis";

tuple = "(", [ atom, [{ atom }] ], ")"
	| atom, [{ atom }];
list = "[", [ atom, [{ atom }] ], "]";

literal = ? identifier ? | variable | string | ? number ?;
variable = "$", ? identifier ?;
string  = ?  delimited by ", ', or ` ?;

figure-delimiter = ? /--[-]+/ ?;
statement-delimiter = ( "\n" - "|" ) | ";;";
property-delimiter = "|";
