statements = [ statement, { statement-delimiter, [ statement ] } ];
statement = expr | define;

define-variable = "let", identifier, "=", expr;
define-function = "let", identifier, ":", variables, function-expr | ( { function-clause, function-expr } );
define = define-variable | define-function;

function-clause = "|", "when", expr-bool;
function-expr = "->", expr;

variables = identifier, { ",", identifier };

expr = term, [ ( "+" | "-" ) expr ];
term = factor, [ ( "*" | "/" ), term ];
factor = [ "-" ], par;
par = ( "(", expr, ")" ) | number | identifier;

expr-bool = expr, ( "=" | ">" | "<" | ">=" | "<=" | "!=" ), expr;

number-int = ? [0-9_]+ ?;
number-point = ? ([0-9_]*)?\.[0-9_]+ ?;
number = number-int | number-point;

identifier = ? [a-zA-Z][a-zA-Z_]* ?;

statement-delimiter = "\n" | ";;";
